# Generated by Django 6.0.2 on 2026-03-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(max_length=50),
        ),
    ]
